---
title: "Final Project - Integrity Page"
author: "May Mishima"
date: today
format: pdf
editor: visual
---

```{r}
#| label: load-packages
#| include: false

library(mosaic)
library(tidyverse)
library(mdsr)
# add other packages here!
```

# Practicing Academic Integrity

If you worked with others or used resources outside of provided course material, such as Generative AI, (anything besides our textbook, course materials in the repo, labs, R help menu) to help complete this assignment, please acknowledge them below using a bulleted list. Remember that according to our class framework, if you engage with Generative AI tools, the tool and date of use must be listed here, and then a complete record of the chat history must be appended to the assignment.

<!-- ~~~~~~~~~~~~~~~~ YOU MAY BEGIN EDITING BELOW THIS LINE ~~~~~~~~~~~~~~~~ -->

*I acknowledge the following individuals with whom I worked on this assignment:*

Name(s) and how they assisted you

-   

*I used the following sources to help complete this assignment:*

Source(s) and where you used them

-   *Network Analysis In R*. RPubs. (n.d.). https://rpubs.com/odenipinedo/network-analysis-in-R. Used when creating networks and setting edges.

-   Nicolas. (2017, December 27). *Saverds() vs write_csv() - a newbie introduction*. OpenGis. https://roelandtn.frama.io/post/saverds-vs-write-csv/. (Accessed December 14). Used when exporting wrangled dataset.

-   Ognyanova, K. (2016). *Network Analysis and Visualization with R and igraph*. Network analysis and visualization with R and igraph. https://kateto.net/netscix2016.html. figuring out network building with transitivity.

-   *Paste: Concatenate strings*. RDocumentation. (n.d.). https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/paste.

    used when creating Shiny App.

-   Shiny themes. (2025, December 14). https://rstudio.github.io/shinythemes/. Used when finding shiny themes.

# Note

Data sources and sources for your *go beyond* should be cited in your report, so they don't need citations here. This is for when you look up code errors or how to do something in ggplot2, etc.
